name: pokedexproject
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.0.6
  fl_chart: ^0.66.0
  connectivity_plus: ^6.1.3
  flutter_local_notifications: ^19.0.0
  google_fonts: ^6.1.0 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
